In [2]:
import duckdb

con = duckdb.connect()
con.execute("LOAD httpfs;")
con.execute("LOAD aws;")
con.execute("""
    SET s3_endpoint='minio:9000';
    SET s3_access_key_id='datalake';
    SET s3_secret_access_key='datalake';
    SET s3_use_ssl=false;
    SET s3_url_style='path';
""")
try:
    print("Searching for buckets and files...")
    # This glob will search for any parquet files in any bucket
    res = con.execute("SELECT * FROM glob('s3://trusted/**/*.parquet')").df()
    if res.empty:
        print("Connected, but no .parquet files found. Check your bucket names.")
    else:
        display(res)
except Exception as e:
    print(f"Still failing: {e}")
    print(f"Connection Failed: {e}")

Searching for buckets and files...

                                                   file
0           s3://trusted/gtfs/calendar/calendar.parquet
1     s3://trusted/gtfs/frequencies/frequencies.parquet
2               s3://trusted/gtfs/routes/routes.parquet
3       s3://trusted/gtfs/stop_times/stop_times.parquet
4                 s3://trusted/gtfs/stops/stops.parquet
...                                                 ...
1673  s3://trusted/sptrans/positions/year=2026/month...
1674  s3://trusted/sptrans/positions/year=2026/month...
1675  s3://trusted/sptrans/positions/year=2026/month...
1676  s3://trusted/sptrans/positions/year=2026/month...
1677  s3://trusted/sptrans/positions/year=2026/month...

[1678 rows x 1 columns]

In [3]:
# Limit DuckDB to 4GB (or whatever suits your machine)
con.execute("SET memory_limit='4GB';")

In [4]:
def query_positions_for_line_vehicle__sentido_day(linha_lt, veiculo_id, linha_sentido, day):
    bucket_name = "trusted"
    app_folder = "sptrans"
    positions_table_name = "positions"
    s3_path = f"s3://{bucket_name}/{app_folder}/{positions_table_name}/**"
    sql = f"""
        SELECT 
            veiculo_ts, linha_lt, veiculo_id, linha_sentido, 
            distance_to_first_stop, distance_to_last_stop, 
            is_circular, lt_origem, lt_destino
        FROM read_parquet('{s3_path}', hive_partitioning = true)
        WHERE linha_lt = '{linha_lt}' and veiculo_id = '{veiculo_id}' and day = '{day}'
        AND linha_sentido = '1'
        ORDER BY veiculo_ts ASC;
    """
    df = con.execute(sql).df()
    
    display(df.shape)
    import pandas as pd
    
    # This forces the display of all 100 rows and all columns
    with pd.option_context('display.max_rows', 200, 'display.max_columns', None):
        display(df.head(200))

In [15]:
def query_positions_for_line_vehicle_day(linha_lt, veiculo_id, day):
    bucket_name = "trusted"
    app_folder = "sptrans"
    positions_table_name = "positions"
    s3_path = f"s3://{bucket_name}/{app_folder}/{positions_table_name}/**"
    sql = f"""
        SELECT 
            veiculo_ts, linha_lt, veiculo_id, linha_sentido, 
            distance_to_first_stop, distance_to_last_stop, 
            is_circular, lt_origem, lt_destino
        FROM read_parquet('{s3_path}', hive_partitioning = true)
        WHERE linha_lt = '{linha_lt}' and veiculo_id = '{veiculo_id}' and day = '{day}'
        ORDER BY veiculo_ts ASC;
    """
    df = con.execute(sql).df()
    
    display(df.shape)
    import pandas as pd
    
    # This forces the display of all 100 rows and all columns
    with pd.option_context('display.max_rows', 200, 'display.max_columns', None):
        display(df.head(200))

In [17]:
def query_positions_for_line_vehicle_day_tz_aware(linha_lt, veiculo_id, day):
    bucket_name = "trusted"
    app_folder = "sptrans"
    positions_table_name = "positions"
    s3_path = f"s3://{bucket_name}/{app_folder}/{positions_table_name}/**"
    sql = f"""
        SELECT 
            (veiculo_ts at time zone 'America/Sao_Paulo'), linha_lt, veiculo_id, linha_sentido, 
            distance_to_first_stop, distance_to_last_stop, 
            is_circular, lt_origem, lt_destino
        FROM read_parquet('{s3_path}', hive_partitioning = true)
        WHERE linha_lt = '{linha_lt}' and veiculo_id = '{veiculo_id}' and day = '{day}'
        ORDER BY veiculo_ts ASC;
    """
    df = con.execute(sql).df()
    
    display(df.shape)
    import pandas as pd
    
    # This forces the display of all 100 rows and all columns
    with pd.option_context('display.max_rows', 200, 'display.max_columns', None):
        display(df.head(200))

In [21]:
linha_lt = '101-10'
veiculo_id = 16018
linha_sentido = '1'
day = '04'

query_positions_for_line_vehicle__sentido_day(linha_lt, veiculo_id, linha_sentido, day)

(0, 9)

Empty DataFrame
Columns: [veiculo_ts, linha_lt, veiculo_id, linha_sentido, distance_to_first_stop, distance_to_last_stop, is_circular, lt_origem, lt_destino]
Index: []

In [22]:
linha_lt = '1017-10'
veiculo_id = 15171
day = '04'
query_positions_for_line_vehicle_day_tz_aware(linha_lt, veiculo_id, day)
# query_positions_for_line_vehicle_day(linha_lt, veiculo_id, day)

(296, 9)

,"main.timezone('America/Sao_Paulo', veiculo_ts)",linha_lt,veiculo_id,linha_sentido,distance_to_first_stop,distance_to_last_stop,is_circular,lt_origem,lt_destino
0,2026-05-04 07:21:35,1017-10,15171,2,6346.0,2747.0,False,PERUS,CONEXÃO VL. IÓRIO
1,2026-05-04 07:23:50,1017-10,15171,2,5991.0,3296.0,False,PERUS,CONEXÃO VL. IÓRIO
2,2026-05-04 07:25:20,1017-10,15171,2,5817.0,3594.0,False,PERUS,CONEXÃO VL. IÓRIO
3,2026-05-04 07:27:35,1017-10,15171,2,5202.0,4065.0,False,PERUS,CONEXÃO VL. IÓRIO
4,2026-05-04 07:29:14,1017-10,15171,2,4837.0,4541.0,False,PERUS,CONEXÃO VL. IÓRIO
5,2026-05-04 07:31:29,1017-10,15171,2,4151.0,5525.0,False,PERUS,CONEXÃO VL. IÓRIO
6,2026-05-04 07:33:44,1017-10,15171,2,4050.0,5654.0,False,PERUS,CONEXÃO VL. IÓRIO
7,2026-05-04 07:35:14,1017-10,15171,2,3782.0,5872.0,False,PERUS,CONEXÃO VL. IÓRIO
8,2026-05-04 07:37:36,1017-10,15171,2,2989.0,6670.0,False,PERUS,CONEXÃO VL. IÓRIO
9,2026-05-04 07:39:21,1017-10,15171,2,2600.0,7110.0,False,PERUS,CONEXÃO VL. IÓRIO
10,2026-05-04 07:41:36,1017-10,15171,2,1681.0,8794.0,False,PERUS,CONEXÃO VL. IÓRIO
11,2026-05-04 07:43:51,1017-10,15171,2,1865.0,9241.0,False,PERUS,CONEXÃO VL. IÓRIO
12,2026-05-04 07:45:21,1017-10,15171,2,1678.0,9412.0,False,PERUS,CONEXÃO VL. IÓRIO
13,2026-05-04 07:47:49,1017-10,15171,2,1208.0,9597.0,False,PERUS,CONEXÃO VL. IÓRIO
14,2026-05-04 07:49:19,1017-10,15171,2,1095.0,9692.0,False,PERUS,CONEXÃO VL. IÓRIO
15,2026-05-04 07:51:54,1017-10,15171,2,1078.0,9983.0,False,PERUS,CONEXÃO VL. IÓRIO
16,2026-05-04 07:53:24,1017-10,15171,2,1147.0,10065.0,False,PERUS,CONEXÃO VL. IÓRIO
17,2026-05-04 07:55:16,1017-10,15171,2,1129.0,10003.0,False,PERUS,CONEXÃO VL. IÓRIO
18,2026-05-04 07:57:57,1017-10,15171,2,385.0,9139.0,False,PERUS,CONEXÃO VL. IÓRIO
19,2026-05-04 07:59:27,1017-10,15171,2,251.0,9133.0,False,PERUS,CONEXÃO VL. IÓRIO
20,2026-05-04 08:01:55,1017-10,15171,2,183.0,9104.0,False,PERUS,CONEXÃO VL. IÓRIO
21,2026-05-04 08:03:25,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
22,2026-05-04 08:05:40,1017-10,15171,2,65.0,8992.0,False,PERUS,CONEXÃO VL. IÓRIO
23,2026-05-04 08:07:55,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
24,2026-05-04 08:09:25,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
25,2026-05-04 08:11:58,1017-10,15171,1,118.0,9012.0,False,PERUS,CONEXÃO VL. IÓRIO
26,2026-05-04 08:13:29,1017-10,15171,1,452.0,9336.0,False,PERUS,CONEXÃO VL. IÓRIO
27,2026-05-04 08:15:44,1017-10,15171,1,268.0,9047.0,False,PERUS,CONEXÃO VL. IÓRIO
28,2026-05-04 08:16:50,1017-10,15171,1,385.0,9139.0,False,PERUS,CONEXÃO VL. IÓRIO
29,2026-05-04 08:16:50,1017-10,15171,1,385.0,9139.0,False,PERUS,CONEXÃO VL. IÓRIO
30,2026-05-04 08:21:47,1017-10,15171,1,1014.0,9935.0,False,PERUS,CONEXÃO VL. IÓRIO
31,2026-05-04 08:23:17,1017-10,15171,1,1028.0,9877.0,False,PERUS,CONEXÃO VL. IÓRIO
32,2026-05-04 08:25:58,1017-10,15171,1,1167.0,9624.0,False,PERUS,CONEXÃO VL. IÓRIO
33,2026-05-04 08:27:52,1017-10,15171,1,1636.0,9427.0,False,PERUS,CONEXÃO VL. IÓRIO
34,2026-05-04 08:29:22,1017-10,15171,1,1736.0,9369.0,False,PERUS,CONEXÃO VL. IÓRIO
35,2026-05-04 08:31:37,1017-10,15171,1,1671.0,8793.0,False,PERUS,CONEXÃO VL. IÓRIO
36,2026-05-04 08:33:52,1017-10,15171,1,2450.0,7232.0,False,PERUS,CONEXÃO VL. IÓRIO
37,2026-05-04 08:35:27,1017-10,15171,1,2959.0,6727.0,False,PERUS,CONEXÃO VL. IÓRIO
38,2026-05-04 08:37:42,1017-10,15171,1,3591.0,6127.0,False,PERUS,CONEXÃO VL. IÓRIO
39,2026-05-04 08:39:57,1017-10,15171,1,3726.0,5947.0,False,PERUS,CONEXÃO VL. IÓRIO
40,2026-05-04 08:41:27,1017-10,15171,1,3754.0,5910.0,False,PERUS,CONEXÃO VL. IÓRIO
41,2026-05-04 08:43:42,1017-10,15171,1,3914.0,5743.0,False,PERUS,CONEXÃO VL. IÓRIO
42,2026-05-04 08:45:57,1017-10,15171,1,3981.0,5700.0,False,PERUS,CONEXÃO VL. IÓRIO
43,2026-05-04 08:47:27,1017-10,15171,1,4195.0,5463.0,False,PERUS,CONEXÃO VL. IÓRIO
44,2026-05-04 08:49:42,1017-10,15171,1,4904.0,4451.0,False,PERUS,CONEXÃO VL. IÓRIO
45,2026-05-04 08:51:57,1017-10,15171,1,5219.0,4046.0,False,PERUS,CONEXÃO VL. IÓRIO
46,2026-05-04 08:53:27,1017-10,15171,1,5914.0,3513.0,False,PERUS,CONEXÃO VL. IÓRIO
47,2026-05-04 08:55:42,1017-10,15171,1,6223.0,2880.0,False,PERUS,CONEXÃO VL. IÓRIO
48,2026-05-04 08:57:50,1017-10,15171,1,6570.0,2534.0,False,PERUS,CONEXÃO VL. IÓRIO
49,2026-05-04 08:59:28,1017-10,15171,1,6720.0,2344.0,False,PERUS,CONEXÃO VL. IÓRIO
50,2026-05-04 09:01:43,1017-10,15171,1,7231.0,1777.0,False,PERUS,CONEXÃO VL. IÓRIO
51,2026-05-04 09:03:58,1017-10,15171,1,7696.0,1242.0,False,PERUS,CONEXÃO VL. IÓRIO
52,2026-05-04 09:05:52,1017-10,15171,1,8089.0,843.0,False,PERUS,CONEXÃO VL. IÓRIO
53,2026-05-04 09:07:22,1017-10,15171,1,8581.0,381.0,False,PERUS,CONEXÃO VL. IÓRIO
54,2026-05-04 09:09:37,1017-10,15171,1,8772.0,158.0,False,PERUS,CONEXÃO VL. IÓRIO
55,2026-05-04 09:11:37,1017-10,15171,1,8911.0,50.0,False,PERUS,CONEXÃO VL. IÓRIO
56,2026-05-04 09:13:52,1017-10,15171,1,8911.0,50.0,False,PERUS,CONEXÃO VL. IÓRIO
57,2026-05-04 09:15:51,1017-10,15171,2,9012.0,398.0,False,PERUS,CONEXÃO VL. IÓRIO
58,2026-05-04 09:17:21,1017-10,15171,2,8761.0,170.0,False,PERUS,CONEXÃO VL. IÓRIO
59,2026-05-04 09:19:18,1017-10,15171,2,7955.0,975.0,False,PERUS,CONEXÃO VL. IÓRIO
60,2026-05-04 09:21:33,1017-10,15171,2,7309.0,1685.0,False,PERUS,CONEXÃO VL. IÓRIO
61,2026-05-04 09:23:19,1017-10,15171,2,6767.0,2282.0,False,PERUS,CONEXÃO VL. IÓRIO
62,2026-05-04 09:25:44,1017-10,15171,2,6419.0,2678.0,False,PERUS,CONEXÃO VL. IÓRIO
63,2026-05-04 09:27:14,1017-10,15171,2,6045.0,3169.0,False,PERUS,CONEXÃO VL. IÓRIO
64,2026-05-04 09:29:29,1017-10,15171,2,5693.0,3699.0,False,PERUS,CONEXÃO VL. IÓRIO
65,2026-05-04 09:31:40,1017-10,15171,2,4904.0,4451.0,False,PERUS,CONEXÃO VL. IÓRIO
66,2026-05-04 09:33:55,1017-10,15171,2,4601.0,4892.0,False,PERUS,CONEXÃO VL. IÓRIO
67,2026-05-04 09:35:25,1017-10,15171,2,4240.0,5401.0,False,PERUS,CONEXÃO VL. IÓRIO
68,2026-05-04 09:37:40,1017-10,15171,2,4050.0,5654.0,False,PERUS,CONEXÃO VL. IÓRIO
69,2026-05-04 09:39:55,1017-10,15171,2,3914.0,5743.0,False,PERUS,CONEXÃO VL. IÓRIO
70,2026-05-04 09:41:39,1017-10,15171,2,3005.0,6655.0,False,PERUS,CONEXÃO VL. IÓRIO
71,2026-05-04 09:43:18,1017-10,15171,2,2578.0,7120.0,False,PERUS,CONEXÃO VL. IÓRIO
72,2026-05-04 09:45:33,1017-10,15171,2,1679.0,8722.0,False,PERUS,CONEXÃO VL. IÓRIO
73,2026-05-04 09:47:48,1017-10,15171,2,1563.0,9450.0,False,PERUS,CONEXÃO VL. IÓRIO
74,2026-05-04 09:49:20,1017-10,15171,2,1208.0,9597.0,False,PERUS,CONEXÃO VL. IÓRIO
75,2026-05-04 09:51:35,1017-10,15171,2,1049.0,9839.0,False,PERUS,CONEXÃO VL. IÓRIO
76,2026-05-04 09:53:39,1017-10,15171,2,1018.0,9948.0,False,PERUS,CONEXÃO VL. IÓRIO
77,2026-05-04 09:55:45,1017-10,15171,2,1129.0,10003.0,False,PERUS,CONEXÃO VL. IÓRIO
78,2026-05-04 09:57:51,1017-10,15171,2,413.0,9124.0,False,PERUS,CONEXÃO VL. IÓRIO
79,2026-05-04 09:59:21,1017-10,15171,2,250.0,9116.0,False,PERUS,CONEXÃO VL. IÓRIO
80,2026-05-04 10:01:53,1017-10,15171,2,183.0,9104.0,False,PERUS,CONEXÃO VL. IÓRIO
81,2026-05-04 10:02:39,1017-10,15171,2,82.0,9011.0,False,PERUS,CONEXÃO VL. IÓRIO
82,2026-05-04 10:02:39,1017-10,15171,2,82.0,9011.0,False,PERUS,CONEXÃO VL. IÓRIO
83,2026-05-04 10:07:25,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
84,2026-05-04 10:09:40,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
85,2026-05-04 10:11:55,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
86,2026-05-04 10:13:25,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
87,2026-05-04 10:15:40,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
88,2026-05-04 10:17:55,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
89,2026-05-04 10:19:25,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
90,2026-05-04 10:21:40,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
91,2026-05-04 10:23:55,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
92,2026-05-04 10:25:25,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
93,2026-05-04 10:27:41,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
94,2026-05-04 10:29:56,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
95,2026-05-04 10:31:26,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
96,2026-05-04 10:33:41,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
97,2026-05-04 10:35:56,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
98,2026-05-04 10:37:26,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
99,2026-05-04 10:39:41,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
100,2026-05-04 10:41:56,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
101,2026-05-04 10:43:26,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
102,2026-05-04 10:45:41,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
103,2026-05-04 10:47:57,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
104,2026-05-04 10:49:27,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
105,2026-05-04 10:51:42,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
106,2026-05-04 10:53:57,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
107,2026-05-04 10:55:27,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
108,2026-05-04 10:57:42,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
109,2026-05-04 10:59:57,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
110,2026-05-04 11:01:27,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
111,2026-05-04 11:03:42,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
112,2026-05-04 11:05:57,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
113,2026-05-04 11:07:28,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
114,2026-05-04 11:09:43,1017-10,15171,2,75.0,9004.0,False,PERUS,CONEXÃO VL. IÓRIO
115,2026-05-04 11:11:58,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
116,2026-05-04 11:13:28,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
117,2026-05-04 11:15:43,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
118,2026-05-04 11:17:58,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
119,2026-05-04 11:19:28,1017-10,15171,2,75.0,9004.0,False,PERUS,CONEXÃO VL. IÓRIO
120,2026-05-04 11:21:25,1017-10,15171,1,118.0,9012.0,False,PERUS,CONEXÃO VL. IÓRIO
121,2026-05-04 11:23:40,1017-10,15171,1,387.0,9316.0,False,PERUS,CONEXÃO VL. IÓRIO
122,2026-05-04 11:25:55,1017-10,15171,1,445.0,9106.0,False,PERUS,CONEXÃO VL. IÓRIO
123,2026-05-04 11:27:41,1017-10,15171,1,899.0,9716.0,False,PERUS,CONEXÃO VL. IÓRIO
124,2026-05-04 11:29:56,1017-10,15171,1,1076.0,9977.0,False,PERUS,CONEXÃO VL. IÓRIO
125,2026-05-04 11:31:25,1017-10,15171,1,994.0,9884.0,False,PERUS,CONEXÃO VL. IÓRIO
126,2026-05-04 11:33:27,1017-10,15171,1,1167.0,9624.0,False,PERUS,CONEXÃO VL. IÓRIO
127,2026-05-04 11:35:31,1017-10,15171,1,1614.0,9434.0,False,PERUS,CONEXÃO VL. IÓRIO
128,2026-05-04 11:37:46,1017-10,15171,1,1585.0,8332.0,False,PERUS,CONEXÃO VL. IÓRIO
129,2026-05-04 11:39:16,1017-10,15171,1,2357.0,7348.0,False,PERUS,CONEXÃO VL. IÓRIO
130,2026-05-04 11:41:46,1017-10,15171,1,3366.0,6353.0,False,PERUS,CONEXÃO VL. IÓRIO
131,2026-05-04 11:43:16,1017-10,15171,1,3609.0,6103.0,False,PERUS,CONEXÃO VL. IÓRIO
132,2026-05-04 11:45:31,1017-10,15171,1,3816.0,5828.0,False,PERUS,CONEXÃO VL. IÓRIO
133,2026-05-04 11:47:46,1017-10,15171,1,3981.0,5700.0,False,PERUS,CONEXÃO VL. IÓRIO
134,2026-05-04 11:49:16,1017-10,15171,1,4410.0,5175.0,False,PERUS,CONEXÃO VL. IÓRIO
135,2026-05-04 11:51:31,1017-10,15171,1,4761.0,4643.0,False,PERUS,CONEXÃO VL. IÓRIO
136,2026-05-04 11:53:39,1017-10,15171,1,5166.0,4109.0,False,PERUS,CONEXÃO VL. IÓRIO
137,2026-05-04 11:55:54,1017-10,15171,1,5693.0,3699.0,False,PERUS,CONEXÃO VL. IÓRIO
138,2026-05-04 11:57:24,1017-10,15171,1,5979.0,3382.0,False,PERUS,CONEXÃO VL. IÓRIO
139,2026-05-04 11:59:39,1017-10,15171,1,6250.0,2849.0,False,PERUS,CONEXÃO VL. IÓRIO
140,2026-05-04 12:01:21,1017-10,15171,1,6535.0,2569.0,False,PERUS,CONEXÃO VL. IÓRIO
141,2026-05-04 12:03:36,1017-10,15171,1,6648.0,2408.0,False,PERUS,CONEXÃO VL. IÓRIO
142,2026-05-04 12:05:50,1017-10,15171,1,7284.0,1715.0,False,PERUS,CONEXÃO VL. IÓRIO
143,2026-05-04 12:07:20,1017-10,15171,1,7674.0,1268.0,False,PERUS,CONEXÃO VL. IÓRIO
144,2026-05-04 12:09:18,1017-10,15171,1,8142.0,790.0,False,PERUS,CONEXÃO VL. IÓRIO
145,2026-05-04 12:11:33,1017-10,15171,1,8671.0,265.0,False,PERUS,CONEXÃO VL. IÓRIO
146,2026-05-04 12:13:23,1017-10,15171,1,8891.0,92.0,False,PERUS,CONEXÃO VL. IÓRIO
147,2026-05-04 12:15:38,1017-10,15171,1,8911.0,50.0,False,PERUS,CONEXÃO VL. IÓRIO
148,2026-05-04 12:17:53,1017-10,15171,1,8911.0,50.0,False,PERUS,CONEXÃO VL. IÓRIO
149,2026-05-04 12:19:23,1017-10,15171,1,8911.0,50.0,False,PERUS,CONEXÃO VL. IÓRIO
150,2026-05-04 12:21:38,1017-10,15171,1,8911.0,50.0,False,PERUS,CONEXÃO VL. IÓRIO
151,2026-05-04 12:23:53,1017-10,15171,1,8911.0,50.0,False,PERUS,CONEXÃO VL. IÓRIO
152,2026-05-04 12:25:23,1017-10,15171,1,8911.0,50.0,False,PERUS,CONEXÃO VL. IÓRIO
153,2026-05-04 12:27:54,1017-10,15171,2,9038.0,345.0,False,PERUS,CONEXÃO VL. IÓRIO
154,2026-05-04 12:29:24,1017-10,15171,2,8874.0,79.0,False,PERUS,CONEXÃO VL. IÓRIO
155,2026-05-04 12:31:39,1017-10,15171,2,8303.0,627.0,False,PERUS,CONEXÃO VL. IÓRIO
156,2026-05-04 12:33:34,1017-10,15171,2,7748.0,1183.0,False,PERUS,CONEXÃO VL. IÓRIO
157,2026-05-04 12:35:49,1017-10,15171,2,7377.0,1606.0,False,PERUS,CONEXÃO VL. IÓRIO
158,2026-05-04 12:37:19,1017-10,15171,2,6987.0,2057.0,False,PERUS,CONEXÃO VL. IÓRIO
159,2026-05-04 12:39:18,1017-10,15171,2,6699.0,2375.0,False,PERUS,CONEXÃO VL. IÓRIO
160,2026-05-04 12:41:48,1017-10,15171,2,6373.0,2720.0,False,PERUS,CONEXÃO VL. IÓRIO
161,2026-05-04 12:43:18,1017-10,15171,2,6045.0,3169.0,False,PERUS,CONEXÃO VL. IÓRIO
162,2026-05-04 12:45:33,1017-10,15171,2,5914.0,3513.0,False,PERUS,CONEXÃO VL. IÓRIO
163,2026-05-04 12:47:48,1017-10,15171,2,5494.0,3867.0,False,PERUS,CONEXÃO VL. IÓRIO
164,2026-05-04 12:49:18,1017-10,15171,2,5219.0,4046.0,False,PERUS,CONEXÃO VL. IÓRIO
165,2026-05-04 12:51:47,1017-10,15171,2,4837.0,4541.0,False,PERUS,CONEXÃO VL. IÓRIO
166,2026-05-04 12:53:17,1017-10,15171,2,4641.0,4817.0,False,PERUS,CONEXÃO VL. IÓRIO
167,2026-05-04 12:55:32,1017-10,15171,2,4195.0,5463.0,False,PERUS,CONEXÃO VL. IÓRIO
168,2026-05-04 12:57:47,1017-10,15171,2,4132.0,5553.0,False,PERUS,CONEXÃO VL. IÓRIO
169,2026-05-04 12:59:17,1017-10,15171,2,4050.0,5654.0,False,PERUS,CONEXÃO VL. IÓRIO
170,2026-05-04 13:01:32,1017-10,15171,2,3726.0,5947.0,False,PERUS,CONEXÃO VL. IÓRIO
171,2026-05-04 13:03:47,1017-10,15171,2,3126.0,6556.0,False,PERUS,CONEXÃO VL. IÓRIO
172,2026-05-04 13:05:29,1017-10,15171,2,2836.0,7040.0,False,PERUS,CONEXÃO VL. IÓRIO
173,2026-05-04 13:07:44,1017-10,15171,2,1855.0,8365.0,False,PERUS,CONEXÃO VL. IÓRIO
174,2026-05-04 13:09:14,1017-10,15171,2,1812.0,9166.0,False,PERUS,CONEXÃO VL. IÓRIO
175,2026-05-04 13:11:29,1017-10,15171,2,1768.0,9343.0,False,PERUS,CONEXÃO VL. IÓRIO
176,2026-05-04 13:13:42,1017-10,15171,2,1283.0,9557.0,False,PERUS,CONEXÃO VL. IÓRIO
177,2026-05-04 13:15:19,1017-10,15171,2,1167.0,9624.0,False,PERUS,CONEXÃO VL. IÓRIO
178,2026-05-04 13:17:32,1017-10,15171,2,1080.0,9988.0,False,PERUS,CONEXÃO VL. IÓRIO
179,2026-05-04 13:19:47,1017-10,15171,2,1025.0,9955.0,False,PERUS,CONEXÃO VL. IÓRIO
180,2026-05-04 13:21:27,1017-10,15171,2,1210.0,10097.0,False,PERUS,CONEXÃO VL. IÓRIO
181,2026-05-04 13:23:42,1017-10,15171,2,863.0,9658.0,False,PERUS,CONEXÃO VL. IÓRIO
182,2026-05-04 13:25:19,1017-10,15171,2,378.0,9160.0,False,PERUS,CONEXÃO VL. IÓRIO
183,2026-05-04 13:27:34,1017-10,15171,2,260.0,9064.0,False,PERUS,CONEXÃO VL. IÓRIO
184,2026-05-04 13:29:49,1017-10,15171,2,312.0,9161.0,False,PERUS,CONEXÃO VL. IÓRIO
185,2026-05-04 13:31:16,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
186,2026-05-04 13:33:31,1017-10,15171,2,68.0,8997.0,False,PERUS,CONEXÃO VL. IÓRIO
187,2026-05-04 13:35:46,1017-10,15171,2,65.0,8992.0,False,PERUS,CONEXÃO VL. IÓRIO
188,2026-05-04 13:37:16,1017-10,15171,2,65.0,8992.0,False,PERUS,CONEXÃO VL. IÓRIO
189,2026-05-04 13:39:31,1017-10,15171,2,65.0,8992.0,False,PERUS,CONEXÃO VL. IÓRIO
190,2026-05-04 13:41:46,1017-10,15171,2,52.0,8975.0,False,PERUS,CONEXÃO VL. IÓRIO
191,2026-05-04 13:43:16,1017-10,15171,2,65.0,8992.0,False,PERUS,CONEXÃO VL. IÓRIO
192,2026-05-04 13:45:31,1017-10,15171,2,65.0,8992.0,False,PERUS,CONEXÃO VL. IÓRIO
193,2026-05-04 13:47:46,1017-10,15171,2,65.0,8992.0,False,PERUS,CONEXÃO VL. IÓRIO
194,2026-05-04 13:49:16,1017-10,15171,2,52.0,8975.0,False,PERUS,CONEXÃO VL. IÓRIO
195,2026-05-04 13:51:40,1017-10,15171,1,287.0,9171.0,False,PERUS,CONEXÃO VL. IÓRIO
196,2026-05-04 13:53:55,1017-10,15171,1,290.0,9209.0,False,PERUS,CONEXÃO VL. IÓRIO
197,2026-05-04 13:55:25,1017-10,15171,1,416.0,9078.0,False,PERUS,CONEXÃO VL. IÓRIO
198,2026-05-04 13:57:54,1017-10,15171,1,843.0,9630.0,False,PERUS,CONEXÃO VL. IÓRIO
199,2026-05-04 13:59:52,1017-10,15171,1,1119.0,10003.0,False,PERUS,CONEXÃO VL. IÓRIO